package com.bsoft.root.mappers;

import com.bsoft.root.entity.PoUser;
import com.bsoft.root.entity.PoUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PoUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_user
     *
     * @mbg.generated Tue Jun 26 15:10:57 CST 2018
     */
    long countByExample(PoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_user
     *
     * @mbg.generated Tue Jun 26 15:10:57 CST 2018
     */
    int deleteByExample(PoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_user
     *
     * @mbg.generated Tue Jun 26 15:10:57 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_user
     *
     * @mbg.generated Tue Jun 26 15:10:57 CST 2018
     */
    int insert(PoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_user
     *
     * @mbg.generated Tue Jun 26 15:10:57 CST 2018
     */
    int insertSelective(PoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_user
     *
     * @mbg.generated Tue Jun 26 15:10:57 CST 2018
     */
    List<PoUser> selectByExample(PoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_user
     *
     * @mbg.generated Tue Jun 26 15:10:57 CST 2018
     */
    PoUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_user
     *
     * @mbg.generated Tue Jun 26 15:10:57 CST 2018
     */
    int updateByExampleSelective(@Param("record") PoUser record, @Param("example") PoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_user
     *
     * @mbg.generated Tue Jun 26 15:10:57 CST 2018
     */
    int updateByExample(@Param("record") PoUser record, @Param("example") PoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_user
     *
     * @mbg.generated Tue Jun 26 15:10:57 CST 2018
     */
    int updateByPrimaryKeySelective(PoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_user
     *
     * @mbg.generated Tue Jun 26 15:10:57 CST 2018
     */
    int updateByPrimaryKey(PoUser record);
}